 
eureka:
  image: 13.127.37.43:5000/amritapuranik/eureka-server:PACKT-SNAPSHOT
  ports:
    - "8761:8761"
    
restaurant-service:
  image: 13.127.37.43:5000/amritapuranik/restaurant-service:PACKT-SNAPSHOT
  ports:
    - "8082:8082"
  links:
    - eureka
